version: '3.9'

services:
  ngnix:
    container_name: ngnix
    build: nginx/
    restart: always
    ports:
      - "80:80"
    networks:
      - net

  frontend1:
    build: frontend1/
    networks:
      - net

  frontend2:
    build: frontend2/
    networks:
      - net

  frontend3:
    build: frontend3/
    networks:
      - net
  
networks:
  net:
